### PR TITLE
translate buttons

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by jensens** [comment]
@pbauer you can run a testing job yourself by logging in into jenkins and passing the URL of this PR to http://jenkins.plone.org/view/All/job/pull-request-5.0/build?delay=0sec
That would simplify the merges. 

Done here: http://jenkins.plone.org/view/All/job/pull-request-5.0/115/ - not needed for 4.3 (is on own branch 2.1.x)

**Comment by pbauer** [comment]
@jensens I did exaclty that with http://jenkins.plone.org/job/pull-request-5.0/114
Better tested twice that not tested at all :smile:

**Comment by jensens** [comment]
oh, almost perfect, just paste the link here and set label to ``pr testing`` so everybody knows.

**Comment by pbauer** [comment]
ok

**Pull request merged**
