### PR TITLE
Backport fix of "ValueError: Circular reference detected" on RelationValue and other fixes of custom_json_handler 

### PR DESCRIPTION
**Pull request by ksuess**

### CODE REVIEW

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM. Thanks for backporting this!

**Comment by ksuess** [comment]
I know you are buzzy, @mauritsvanrees. Do you think you could find the time to make a 3.x release next days? That would be great, thank you.

**Comment by mauritsvanrees** [comment]
@ksuess Sure, no problem. I have released `plone.app.content` 3.8.10 and have put it in coredev 5.2.

**Comment by ksuess** [comment]
> @ksuess Sure, no problem. I have released `plone.app.content` 3.8.10 and have put it in coredev 5.2.

You're the best!

**Pull request merged**
