### PR TITLE
Fix `select_default_page` in VHM environments

### PR DESCRIPTION
**Pull request by petschki**
Fixes https://github.com/plone/Products.CMFPlone/issues/4001

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by 1letter — APPROVED** [review]
LGTM, tested and all is fine!

**Review by mauritsvanrees — APPROVED** [review]
Thanks for adding the test!

**Comment by mauritsvanrees** [comment]
I have released `plone.app.content` 4.1.7 with this.
I will update plone coredev shortly.

**Pull request merged**
