### PR TITLE
Do not setDefaultPage in rename handler, there is already an subscrib…

### PR DESCRIPTION
**Pull request by jensens**
…er doing so in Products.CMFDynamicViewFTI.

### CODE REVIEW

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/172/

**Comment by pbauer** [comment]
@jensens I remember the default page got lost during a rename that is why I added it here. Did you find out what was wrong before?

**Comment by jensens** [comment]
@pbauer I found that everything works fine without setting it here (test runs local). Looks like the problem was something different then, maybe event/subscriber related? I any case if it happens again the real cause must be found. The events from `manage_renameObjects` must not be ignored in any case.

**Comment by pbauer** [comment]
@jensens ok, I did not know about the event in Products.CMFDynamicViewFTI.

**Comment by jensens** [comment]
@pbauer I did not know them too - just digged yesterday through code and call stacks and wondered about the frequent calls of setDefaultPage...

**Pull request merged**
