### PR TITLE
Follow default_page_types setting when showing the items that can be selected as default page

### LINKED ISSUE #182: All items are shown in select default page form regardless the registry setting to filter items with a given content-type
There is a registry setting to filter the items available to be selected as default page according to their content-type.

Anyway the code here adds them to the list:

https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/selection.py#L128

If all checks fail, the item is added to the result list.

I will try to write a test and a fix.

### PR DESCRIPTION
**Pull request by erral**
Fixes #182 

Merge together: https://github.com/plone/Products.CMFPlone/pull/2955

### CODE REVIEW

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
@jenkins-plone-org please run jobs

**Comment by erral** [comment]
This requires a change in Plone tests:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/tests/browser_collection_views.txt#L109

Here it is checked that a Collection can be set as a default page, and when enforcing the check on selectable_content_types this assumption is wrong.

So we either add Collection as a default selectable content-type or change the test.

**Comment by erral** [comment]
I prepared a PR for CMFPlone here: https://github.com/plone/Products.CMFPlone/pull/2955

**Comment by erral** [comment]
The combined test is green : https://jenkins.plone.org/job/pull-request-5.2/586/

**Comment by mauritsvanrees** [comment]
This needs to be merged together with the matching CMFPlone fix, right?
I will not do that just now, because I am about to lose internet connection. I will get back to this, unless someone beats me to it.

**Comment by erral** [comment]
Yes, but check also the upgrade step that @jensens mentioned at https://github.com/plone/Products.CMFPlone/pull/2955#pullrequestreview-299264444

**Pull request merged**
