### PR TITLE
Fixup test_delete_wrong_object_by_acquisition_with_action.

### PR DESCRIPTION
**Pull request by jaroel**
We won't publish acquired content items anymore. Refs https://github.com/zopefoundation/Products.CMFCore/pull/129

### CODE REVIEW

**Comment by jaroel** [comment]
@plone/ai-team Could someone help with that `pre-commit.ci - pr — error during ci config` error?

**Comment by gforcada** [comment]
Fixed, I disabled `pre-commit` hook, as it is still not merged from #262

**Comment by gforcada** [comment]
🤔 seems it is still there, probably if you push a new commit it will now show up again 🍀

**Comment by jaroel** [comment]
@jenkins-plone-org please run jobs

**Comment by polyester** [comment]
pre-commit-ci wasn't enabled on plone.app.content, I enabled it on that repo

**Comment by gforcada** [comment]
@polyester no, I just disabled it on purpose, because it still needs #262 to get merged first 😅

**Review by mauritsvanrees — APPROVED** [review]

**Pull request merged**
