### PR TITLE
Fix escaped html entities in vocabulary items

### PR DESCRIPTION
**Pull request by petschki**
see https://github.com/plone/Products.CMFPlone/issues/3874

I tried to change the `parser` here https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/transforms/safe_html.py#L187 to `html.XHTMLParser(encoding="utf-8", resolve_entities=False, recover=True)` but this removes all entities in the string and leads to many testing failures.

Note that this only affects `@@getVocabulary` BrowserView when no attributes are passed in the request ~~and for this special `&` case. Wonder if there is a more generic solution for more cases out there?~~ Update: I think its ok to unescape all entities.

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Seems okay, but I am investigating possible security implications of this PR, so have reverted it to Draft status for now.  We have had a few security fixes in this area the past few years, so it is tricky to be sure if something is safe.

**Comment by jensens** [comment]
Looks good to me. It solves escaping, scrubbing is still in there. I do not see how this could touch any security relevant as it delivers vocabs as JSON to the browser. I am not sure if the `id` needs this.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by petschki** [comment]
@mauritsvanrees I'd like to merge this. Do you still have security concers?

**Review by mauritsvanrees — APPROVED** [review]
I don't see any extra security issues introduced by this.

**Pull request merged**
