### PR TITLE
folder_contents filter should not use SearchableText, but Title

### PR DESCRIPTION
**Pull request by frapell**
This is how it works today:

Screenshot_20191211_151300

This is how it will work, if this PR is merged

Screenshot_20191211_151755

Screenshot_20191211_151824

### CODE REVIEW

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@jensens @ale-rt Hey guys, would you like to share your thoughts about this? (BTW, I was wondering if I should submit a PLIP for this change... it sounds very small to do that, but let me know what you think)

**Comment by frapell** [comment]
Also, forgot to mention in the description of the PR, this is for issue #189

**Comment by mauritsvanrees** [comment]
I would say that using the SearchableText index here is not a bug.  So this is not a bug fix, but a change in behaviour. So an enhancement or tiny feature.
I would not be surprised if a small percentage of users will not like this change. I am not one of them though. :-)

**Comment by frapell** [comment]
@mauritsvanrees Several customers have reported how they see unexpected results when filtering in the folder_contents, so I don't think someone would actually want the current behavior, I think it was mostly an oversight, I also wouldn't consider this a bugfix...

**Comment by jensens** [comment]
Difficult. At least it is feature-like, because behavior changes. It is not worth a PLIP, its an enhancement.

So, there might be users out there relying on fulltext search here. For them it would be a breaking change. Now we can deal with this in two ways: 1) Do not care about it 2) make it configurable (registry).

I tend to not do not care, so I would make it configurable, keeping it the way it is for existing installations and for new ones searching for Title only.

This is some effort for such a minimal change, yes. But well.... you asked me for my thoughts.

**Comment by frapell** [comment]
@jensens Well... just to confirm... this would *only* affect the "filtering" in folder_contents. The main Plone search would still be using the SearchableText. Also, there's still clicking the magnifying glass to change the query in order to choose something else besides title if so it is desired...

image


Adding a configuration to the control panel as you describe, would require to add an upgrade step, which might make it a candidate for PLIP'ing

**Comment by jensens** [comment]
> this would only affect the "filtering" in folder_contents.

Yes, I know.

> Also, there's still clicking the magnifying glass to change the query in order to choose something else besides title if so it is desired...

So, you're change in fact just changes the default of the search there?

**Comment by frapell** [comment]
@jensens That's correct... This would only change the default index used when you don't specify one from the magnifying glass.

**Pull request merged**
