### PR TITLE
Require cmf.ModifyPortalContent for content_status_history

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
http://jenkins.plone.org/job/pull-request-5.0/150/

**Comment by jensens** [comment]
oh yes!
test here: http://jenkins.plone.org/job/pull-request-5.0/165/

**Comment by jensens** [comment]
Seems like `plone.app.iterate.tests.browser.rst` assumes anonymous access, which is a wrong test imo.

**Comment by pbauer** [comment]
Test: http://jenkins.plone.org/job/pull-request-5.0/362/

**Comment by gforcada** [comment]
There seems to be some errors due to duplicated profiles registered... rings a bell to anyone?

**Comment by pbauer** [comment]
The failures might be unrelated. 
Retest: http://jenkins.plone.org/job/pull-request-5.0/3​66

**Pull request merged**
