### PR TITLE
Added registry settings for IContentSettings. 

### PR DESCRIPTION
**Pull request by djay**
replaces https://github.com/plone/plone.app.content/pull/3

### CODE REVIEW

**Comment by jensens** [comment]
just started the tests here http://jenkins.plone.org/view/All/job/pull-request/145/
but needs a rebase, just realized after running the tests :/

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request-5.0/53/

**Comment by thet** [comment]
I guess, this targets Plone 5, does it?
Then this should go as controlpanel including tests into Products.CMFPlone?
But then, we don't have a widget for a dict field, do we?

**Comment by jensens** [comment]
I'am lost with this one, what is the plan here?

**Comment by vangheem** [comment]
This would be nice to have but it should be implemented in Products.CMFPlone. Since it's old, perhaps we should close this and wait for a new PR?

please feel free to re-open and send me hate mail if you disagree.

**Pull request closed without merging**
